# Generated by Django 5.2.1 on 2025-05-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_analytic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
